apps/snacks/urls.py
from django.conf.urls import url, include
from . import views           # This line is new!
urlpatterns = [
    url(r'^$', views.index, name='index'),    
    url(r'^new/(?P<id>[0-9]+)?$', views.new, name='new'),
    # url(r'^create$', views.create, name='create'),
    url(r'^create$', views.create, name='create'),
    url(r'^cart$', views.cart, name='cart'),
    url(r'^checkout$', views.checkout, name='checkout'),
    url(r'^newlyadded$', views.newlyadded, name='newlyadded'),
    url(r'^top$', views.top, name='top'),
    url(r'^inventory$', views.inventory, name='inventory'),
    url(r'^mostreviewed$', views.mostreviewed, name='mostreviewed'),
    url(r'^(?P<id>[0-9]+)/create$', views.review, name='review'),
    url(r'^(?P<id>[0-9]+)/quantity$', views.quantity, name='quantity'),
    url(r'^(?P<id>[0-9]+)/add$', views.add, name='add'),
    url(r'^(?P<id>[0-9]+)$', views.show, name='show'),
    url(r'^(?P<id>[0-9]+)/redit$', views.redit, name='redit'),
    url(r'^(?P<id>[0-9]+)/update$', views.update, name='update'),
    url(r'^reviews/(?P<id>[0-9]+)/update$', views.rupdate, name='rupdate'),
    url(r'^(?P<id>[0-9]+)/destroy$', views.destroy, name='destroy'),
    url(r'^(?P<id>[0-9]+)/destroysnack$', views.destroysnack, name='destroysnack'),
    url(r'^search$', views.search, name='search')
]

apps/users/urls.py
from django.conf.urls import url, include
from . import views           # This line is new!
urlpatterns = [
    url(r'^$', views.index, name='index'),    
    url(r'^login$', views.login, name='login'),
    url(r'^register$', views.register, name='register'),
    url(r'^(?P<id>[0-9]+)$', views.show, name='show'),
    url(r'^(?P<id>[0-9]+)/update$', views.update, name='update'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^admin$', views.admin, name='admin'),
    url(r'^addadmin/(?P<id>[0-9]+)$', views.addadmin, name='addadmin')
]

ordering/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('apps.users.urls', namespace='users')),
    url(r'^snacks/', include('apps.snacks.urls', namespace='snacks')),
    url(r'^', include('apps.users.urls')),
]

apps/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import re
import bcrypt

# Create your models here.
class UserManager(models.Manager):
    def register_validator(self, data):
        errors = {}
        if len(data['first_name']) < 2 or any(char.isdigit() for char in data['first_name']) :
            errors['first_name'] = "Invalid First Name"
        if len(data['last_name']) < 2 or any(char.isdigit() for char in data['last_name']) :
            errors['last_name'] = "Invalid Last Name"
        if len(data['alias']) < 2 :
            errors['alias'] = "Invalid Alias"   
        if len(data['email']) < 0 or re.match(r"[^@]+@[^@]+\.[^@]+", data['email']) == None :
            errors['email'] = "Invalid Email"       
        if len(data['password']) < 8 :
            errors['password'] = "Password is too short"
        if data['password'] != data['confirmation'] :
            errors['confirmation'] = "password and confirmation aren't the same"
        if self.filter(email=data['email']).count() > 0:
            errors['email'] = "Someone with that email is already registered" 
        return errors
    def login_validator(self, data):
        errors = {} 
        if len(data['lpassword']) < 8 :
            errors['lpassword'] = "Password is too short"          
        if len(data['lemail']) < 0 or re.match(r"[^@]+@[^@]+\.[^@]+", data['lemail']) == None :
            errors['lemail'] = "Invalid Email"  
        elif self.filter(email=data['lemail']).count() == 0:
            errors['lemail'] = "You haven't registered with that email yet" 
        elif not bcrypt.checkpw(data['lpassword'].encode(), self.filter(email=data['lemail'])[0].password.encode()):
            errors['lpassword'] = "Your password doesn't match"   
        return errors

class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    alias = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    is_admin = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # *************************b
    # Connect an instance of BlogManager to our Blog model overwriting
    # the old hidden objects key with a new one with extra properties!!!
    objects = UserManager()

apps/users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib import messages
from django.shortcuts import render, redirect
import bcrypt
from models import *

# Create your views here.
def index(request) :

    return render(request, 'users/index.html')
   
def register(request) :
    if 'first_name' in request.session :
        request.session.pop('first_name')
    if 'last_name' in request.session :
        request.session.pop('last_name')
    if 'alias' in request.session :
        request.session.pop('alias')
    if 'email' in request.session :
        request.session.pop('email')
    if 'password' in request.session :
        request.session.pop('password')
    if 'confirmation' in request.session :
        request.session.pop('confirmation')
    if 'lemail' in request.session :
        request.session.pop('lemail')
    if 'lpassword' in request.session :
        request.session.pop('lpassword')
    if 'review' in request.session :
        request.session.pop('review')
    errors = User.objects.register_validator(request.POST)
    if len(errors):
        for tag, error in errors.iteritems():
            request.session[tag] = error
        return redirect('/')
    else:
        password = bcrypt.hashpw(request.POST['password'].encode(), bcrypt.gensalt())
        user = User.objects.create(first_name=request.POST['first_name'], last_name=request.POST['last_name'], alias=request.POST['alias'], email=request.POST['email'], password=password, is_admin=False)
        user.save()
        request.session['current_user'] = User.objects.filter(email=request.POST['email'])[0].id
        return redirect('/snacks')

def login(request) :
    if 'first_name' in request.session :
        request.session.pop('first_name')
    if 'last_name' in request.session :
        request.session.pop('last_name')
    if 'alias' in request.session :
        request.session.pop('alias')
    if 'email' in request.session :
        request.session.pop('email')
    if 'password' in request.session :
        request.session.pop('password')
    if 'confirmation' in request.session :
        request.session.pop('confirmation')
    if 'lemail' in request.session :
        request.session.pop('lemail')
    if 'lpassword' in request.session :
        request.session.pop('lpassword')
    if 'review' in request.session :
        request.session.pop('review')
    errors = User.objects.login_validator(request.POST)
    if len(errors):
        for tag, error in errors.iteritems():
            request.session[tag] = error
        return redirect('/')
    else:
        request.session['current_user'] =  User.objects.filter(email=request.POST['lemail'])[0].id
        return redirect('/snacks')

def show(request, id):
    count = len(User.objects.filter(id=id)[0].review_user.all())
    context = {
        'user' : User.objects.filter(id=id)[0],
        'count' : count
    }
    return render(request, 'users/show.html', context)

def update(request, id):

    return redirect('users/show')

def logout(request):
    request.session.clear()
    return render(request, 'users/index.html')

def admin(request):

    users = User.objects.filter(is_admin= False)
    context = {
        'users': users,
        'user' : User.objects.filter(id=request.session['current_user'])[0]
    }

    return render(request, 'users/admin.html', context)


def addadmin(request, id):
    user= User.objects.filter(id = id)[0]
    user.is_admin= True
    user.save()

    return redirect ('admin')

apps/users/templates/users/admin.html
<!DOCTYPE html> {% load static %}
<html>

<head>
    <title>Users</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
        crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
        crossorigin="anonymous"></script>
    <link rel='stylesheet' href="{% static 'users/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'snacks:index' %}">Snacks</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:show' user.id %}">Account</a>
                </li>
                {% if user.is_admin %}
                <li class="nav-item">
                        <a class="nav-link" href="{% url 'snacks:new' %}">Add Snack</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'snacks:cart' %}">Shopping Cart</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" style='color:rgb(187, 49, 49);' href="{% url 'users:admin' %}">Add Admins</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'snacks:inventory' %}">Inventory</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                </li>
            </ul>
            <span class="navbar-text">
                <form class="form-inline" action="{% url 'snacks:search' %}" method="POST">
                    {% csrf_token %}

                    <input class="form-control mr-sm-2" type="search" name='search' placeholder="Search snack.." aria-label="Search">
                    <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>

                </form>
            </span>
        </div>
    </nav>
    <br>

<div class="container">
   
    <div class="card-body">
        <div class="row">
           {% for user in users %}

            <div class="col" style='margin-left: 18px; margin-top: 20px;'>
                <div class="card" style="width: 18em">
                    <div class="card-body">
                        <h5>
                            <p>{{user.first_name}} {{user.last_name}}</p> 
                        </h5>
                        <p>Email: {{user.email}}</p>
                        <p>User Name : {{user.alias}}</p>
                    
                        <form action="{% url 'users:addadmin' user.id %}" method="POST">
                            {% csrf_token %}
                            
                            <input type="submit" value="Add Admin">
                        </form>
                       
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>


    </div>



</div>





</body>

</html>

apps/users/templates/users/index.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
        <title>Users</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
        <link rel='stylesheet' href="{% static 'users/style.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	</head>
	<body>

        <div class="container">
            <div class="row">
                <div class="col-md-4 col-centered">
                    <h1>Registration</h1>
                    <form action="{% url 'users:register' %}" method="POST">
                        <div class="form-group">
                            {% csrf_token %}
                            First Name: <input type="text" name="first_name" class="form-control">
                            {% if request.session.name %}
                            <p>{{request.session.name}}</p>
                            {% endif %}
                            Last Name: <input type="text" name="last_name" class="form-control">
                            {% if request.session.name %}
                            <p>{{request.session.name}}</p>
                            {% endif %}
                            Alias: <input type="text" name="alias"class="form-control">
                            {% if request.session.alias %}
                            <p>{{request.session.alias}}</p>
                            {% endif %}
                            Email: <input type="email" name="email"class="form-control">
                            {% if request.session.email %}
                            <p>{{request.session.email}}</p>
                            {% endif %}
                            Password: <input type="password" name="password"class="form-control">
                            {% if request.session.password %}
                            <p>{{request.session.password}}</p>
                            {% endif %}
                            Confirmation: <input type="password" name="confirmation"class="form-control">
                            <input type="submit" value="Register" class="form-control">
                        </div>
                    </form>
                </div>
                <div class="col-md-4 col-centered">
                    <h1>Login</h1>
                    <form action="{% url 'users:login' %}" method="POST">
                        <div class="form-group">
                            {% csrf_token %}
                            Email: <input type="email" name="lemail" class="form-control">
                            {% if request.session.lemail %}
                            <p>{{request.session.lemail}}</p>
                            {% endif %}
                            Password: <input type="password" name="lpassword" class="form-control">
                            {% if request.session.lpassword %}
                            <p>{{request.session.lpassword}}</p>
                            {% endif %}
                            <input type="submit" value="Login" class="form-control">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </body>
</html>

apps/users/templates/users/show.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		<title>Account</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
		 crossorigin="anonymous">
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
		 crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
		 crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
		 crossorigin="anonymous"></script>
		<link rel='stylesheet' href="{% static 'users/style.css' %}">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	</head>
	<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<a class="navbar-brand" href="{% url 'snacks:index' %}">Snacks</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText"
	 aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarText">
		<ul class="navbar-nav mr-auto">

			<li class="nav-item">
				<a style='color:rgb(187, 49, 49);' class="nav-link" href="{% url 'users:show' user.id %}">Account</a>
			</li>
			{% if user.is_admin %}
			<li class="nav-item">
					<a class="nav-link" href="{% url 'snacks:new' %}">Add Snack</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'snacks:cart' %}">Shopping Cart</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'users:admin' %}">Add Admins</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'snacks:inventory' %}">Inventory</a>
				</li>
			{% endif %}
			<li class="nav-item">
				<a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
			</li>
		</ul>
		<span class="navbar-text">
			<form class="form-inline" action="{% url 'snacks:search' %}" method="POST">
				{% csrf_token %}

				<input class="form-control mr-sm-2" type="search" name='search' placeholder="Search snack.." aria-label="Search">
				<button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>

			</form>
		</span>
	</div>
</nav>
<br>

<div class="container">
	{% if user.is_admin %}
	<p style='color:rgb(187, 49, 49);'>You are an Admin</p>
	{% endif %}
	   <p>User Alias: {{user.alias}} </p>
	   <p>Name: {{user.first_name}} {{user.last_name}} </p>
	   <p>Email: {{user.email}} </p>
	   <p>Total Reviews: {{count}} </p>
</div>
    </body>
</html>