apps/snacks/urls.py
from django.conf.urls import url, include
from . import views           # This line is new!
urlpatterns = [
    url(r'^$', views.index, name='index'),    
    url(r'^new/(?P<id>[0-9]+)?$', views.new, name='new'),
    # url(r'^create$', views.create, name='create'),
    url(r'^create$', views.create, name='create'),
    url(r'^cart$', views.cart, name='cart'),
    url(r'^checkout$', views.checkout, name='checkout'),
    url(r'^newlyadded$', views.newlyadded, name='newlyadded'),
    url(r'^top$', views.top, name='top'),
    url(r'^inventory$', views.inventory, name='inventory'),
    url(r'^mostreviewed$', views.mostreviewed, name='mostreviewed'),
    url(r'^(?P<id>[0-9]+)/create$', views.review, name='review'),
    url(r'^(?P<id>[0-9]+)/quantity$', views.quantity, name='quantity'),
    url(r'^(?P<id>[0-9]+)/add$', views.add, name='add'),
    url(r'^(?P<id>[0-9]+)$', views.show, name='show'),
    url(r'^(?P<id>[0-9]+)/redit$', views.redit, name='redit'),
    url(r'^(?P<id>[0-9]+)/update$', views.update, name='update'),
    url(r'^reviews/(?P<id>[0-9]+)/update$', views.rupdate, name='rupdate'),
    url(r'^(?P<id>[0-9]+)/destroy$', views.destroy, name='destroy'),
    url(r'^(?P<id>[0-9]+)/destroysnack$', views.destroysnack, name='destroysnack'),
    url(r'^search$', views.search, name='search')
]

apps/users/urls.py
from django.conf.urls import url, include
from . import views           # This line is new!
urlpatterns = [
    url(r'^$', views.index, name='index'),    
    url(r'^login$', views.login, name='login'),
    url(r'^register$', views.register, name='register'),
    url(r'^(?P<id>[0-9]+)$', views.show, name='show'),
    url(r'^(?P<id>[0-9]+)/update$', views.update, name='update'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^admin$', views.admin, name='admin'),
    url(r'^addadmin/(?P<id>[0-9]+)$', views.addadmin, name='addadmin')
]

ordering/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('apps.users.urls', namespace='users')),
    url(r'^snacks/', include('apps.snacks.urls', namespace='snacks')),
    url(r'^', include('apps.users.urls')),
]

apps/snacks/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from ..users.models import User
from django import template
import json


# Create your models here.
# class ReviewManager(models.Manager):

class SnackManager(models.Manager):
    def snack_validator(self, data):
        errors = {}
        if len(data['name']) < 2 :
            errors['name'] = "That's not a snack name"
        if 'nbrand' in data :
            if data['nbrand'] < 1 :
                errors['nbrand'] = 'Not a valid brand'
        else :
            if len(data['brand']) < 1 :
                errors['brand'] = "That's not a valid brand"
        if 'ncategory' in data :
            if data['ncategory'] < 1 :
                errors['ncategory'] = 'Not a valid category'
        else :
            if len(data['category']) < 1 :
                errors['category'] = "That's not a valid category"

        return errors

    def avg_rating(self, snack) :
        reviews = snack.review_snack.all()
        total = 0
        for review in reviews :
            total += review.rating
        if len(reviews) == 0 :
            length = 1
        else :
            length = len(reviews)
        return round(float(total)/float(length),1) 

    def review_validator(self, data):
        errors = {}
        user = User.objects.filter(id=data[0])[0]
        snack = Snack.objects.filter(id=data[1])[0]
        if len(Review.objects.filter(user=user, snack=snack)) > 0:
            errors['review'] = 'You already reviewed this snack!'
        return errors

# class InventoryManager(models.Manager):
#     def inventory_validator(self, data):
#         errors = {}
#         if data['quantity'] < 1 :
#             errors['quantity'] = "Not a valid quantity"
#         if len(data['snack']) < 1 :
#             errors['snack'] = "That's not a snack"
#         return errors


class Brand(models.Model):
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    # objects = BrandManager()

class Category(models.Model):
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    # objects = CategoryManager()

class Snack(models.Model):
    name = models.CharField(max_length=255)
    price = models.FloatField()
    total_purchased_amount = models.IntegerField()
    brand = models.ForeignKey(Brand, related_name='brand')
    picture_url = models.CharField(max_length=255)
    category = models.ForeignKey(Category, related_name='category')
    created_at = models.DateTimeField(auto_now_add=True)
    quantity = models.IntegerField()
    avg = 0
    def toJSON(self):
        return json.dumps(self, default=lambda o: o.__dict__, 
            sort_keys=True, indent=4)
    objects = SnackManager()

# class Inventory(models.Model):
#     quantity = models.IntegerField()
#     snack = models.ForeignKey(Snack, related_name='inventory_snack')
#     created_at = models.DateTimeField(auto_now_add=True)
    # ohbjects = InventoryManager()

class Review(models.Model):
    content = models.TextField()
    rating = models.IntegerField()
    user = models.ForeignKey(User, related_name='review_user')
    snack = models.ForeignKey(Snack, related_name='review_snack')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # objects = ReviewManager()

# @register.simple_tag

apps/snacks/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db.models import Count, Avg
from django.shortcuts import render, redirect
from operator import itemgetter
from models import Review, Snack, SnackManager, Category, Brand
from ..users.models import User, UserManager
import requests
import datetime
import openfoodfacts
from django.utils import timezone
# Create your views here.
def index(request): 
    if 'review' in request.session :
        request.session.pop('review')
    snacks = Snack.objects.all().order_by('name')
    for snack in snacks :
        snack.avg = Snack.objects.avg_rating(snack)

    context = {
        'user' : User.objects.filter(id=request.session['current_user'])[0],
        'snacks' : snacks
    }

    return render(request, 'snacks/index.html', context)

def new(request, id):
    context = {
            'user' : User.objects.filter(id=request.session['current_user'])[0],
            'categories' : Category.objects.all(),
            'brands' : Brand.objects.all()
        }
    if id == None :
        context['snack'] = {}
        
    else :
        search_result = openfoodfacts.products.get_product(id)
        snack = {}
        snack['search'] = ''
        snack['id'] = search_result['product']['code']
        snack['name'] =  search_result['product']['product_name']
        if ' brands' in search_result['product'] :
            snack['brand'] = search_result['product']['brands']
        snack['picture_url'] =  search_result['product']['image_front_url']
        context['snack'] = snack
    

    return render(request, 'snacks/new.html', context)

def create(request):
    errors = Snack.objects.snack_validator(request.POST)
    if len(errors):
        for tag, error in errors.iteritems():
            request.session[tag] = error
        return redirect('/snacks/new')
    else:
        if len(request.POST['nbrand']) < 1 :
            brand = Brand.objects.filter(name=request.POST['brand'])[0]         
        else :
            brand = Brand.objects.create(name=request.POST['nbrand'])
            brand.save()
        if len(request.POST['ncategory']) < 1 :
            category = Category.objects.filter(name=request.POST['category'])[0]
        else :
            category = Category.objects.create(name=request.POST['ncategory'])
            category.save()
        snack = Snack.objects.create(name=request.POST['name'], picture_url=request.POST['picture_url'], price=0, total_purchased_amount=0, brand=brand, category=category, quantity=0)
        snack.save()

    return redirect('/snacks/{}'.format(Snack.objects.filter(name=snack.name)[0].id))

def review(request, id):
    if 'review' in request.session :
        request.session.pop('review')
    user = User.objects.filter(id=request.session['current_user'])[0]
    snack = Snack.objects.filter(id=id)[0]
    data = [user.id, snack.id]
    errors = Snack.objects.review_validator(data)
    if len(errors):
        for tag, error in errors.iteritems():
            request.session[tag] = error        
        return redirect('/snacks/{}'.format(snack.id))
    else :
        review = Review.objects.create(content=request.POST['content'], rating=request.POST['rating'], user=user, snack=snack)
        review.save()
        return redirect('/snacks/{}'.format(snack.id))

def show(request, id):
    snack = Snack.objects.filter(id=id)[0]
    snack.avg = Snack.objects.avg_rating(snack)
    context = {
        'user' : User.objects.filter(id=request.session['current_user'])[0],
        'snack' : snack,
        'reviews' : Snack.objects.filter(id=id)[0].review_snack.all()
    }
    

    return render(request, 'snacks/show.html', context)

def update(request, id):
        
    return redirect('/snacks/index')

def redit(request, id):
    if 'review' in request.session :
        request.session.pop('review')
    context = {
        'user' : User.objects.filter(id=request.session['current_user'])[0],
        'review' : Review.objects.filter(id=id)[0]
    }
    
    return render(request, 'snacks/edit.html', context)

def rupdate(request, id):
    if 'review' in request.session :
        request.session.pop('review')
    review = Review.objects.filter(id=id)[0]
    if len(request.POST['content']) < 1 :
        content = review.content
    else :
        content = request.POST['content']
    if 'rating' in request.POST :
        rating = request.POST['rating']
    else :
        rating = review.rating
    review.content = content
    review.rating = rating
    review.updated_at = timezone.now()
    review.save()
    snack = review.snack
    return redirect('/snacks/{}'.format(snack.id))

def cart(request):
    # request.session.pop('cart')
    if 'cart' not in request.session :
        request.session['cart'] = {}
    context = {
        'user' : User.objects.filter(id=request.session['current_user'])[0],
        'cart' : request.session['cart']
    }
    # print request.session['cart']
    return render(request, 'snacks/cart.html', context)

def add(request, id):
    if 'cart' not in request.session :
        request.session['cart'] = {}
    snack = Snack.objects.filter(id=id)[0]
    cart = request.session['cart']
    # request.session.pop('cart')
    formatted_snack = {
                        'id' : snack.id,
                        'name' : snack.name,
                        'total_purchased_amount' : snack.total_purchased_amount,
                        'brand' : snack.brand.name,
                        'picture_url' : snack.picture_url,
                        'category' : snack.category.name,
                        'quantity' : snack.quantity,
                        'avg' : Snack.objects.avg_rating(snack)
                    }

    cart[formatted_snack['id']] = formatted_snack
    request.session['cart'] = cart
    request.session.modified = True
    print request.session['cart']
    # context = {
    #     'user' : User.objects.filter(id=request.session['current_user'])[0],
    #     'cart' : request.session['cart']
    # }
    return redirect('/snacks/')

# def checkout(request) :


def destroy(request, id):
    if 'review' in request.session :
        request.session.pop('review')
    review = Review.objects.filter(id=id)[0]
    snack = review.snack
    review.delete()
    return redirect('/snacks/{}'.format(snack.id))

def search(request):
    search_result = openfoodfacts.products.advanced_search({
                                                            "search_terms":request.POST['search']
                                                        })
    # search_result = openfoodfacts.products.search(request.POST['search'], 1, 20, 'unique_scans','united states')
    # print search_result['products']
    snacks = []
    for val in search_result['products']:
        if 'image_front_url' in val :
            if not len(val['image_front_url']) == 0:
                if val['product_name'] == 'Full on flavour - Four cheese & red onion':
                    print val['image_front_url']
                snack = {}
                snack['search'] = ''
                snack['id'] = val['code']
                snack['name'] =  val['product_name']
                if ' brands' in val :
                    snack['brand'] = val['brands']
                snack['picture_url'] =  val['image_front_url']
                snacks.append(snack)
    our_snacks = Snack.objects.filter(name__contains='{}'.format(request.POST['search']))
    for snack in our_snacks :
        snack.avg = Snack.objects.avg_rating(snack)
        snacks.append(snack)
    context = {
        'user' : User.objects.filter(id=request.session['current_user'])[0],
        'snacks' : snacks
    }
    return render(request, 'snacks/search.html', context)

def destroysnack(request, id):
    if str(id) in request.session['cart'] :
        del request.session['cart'][str(id)]
        request.session.modified = True
    return redirect('/snacks/cart')

def newlyadded(request):

    context = {
    'snacks': Snack.objects.all().order_by('created_at'),
    'user' : User.objects.filter(id=request.session['current_user'])[0]
    }

    return render(request, 'snacks/index.html', context)

def top(request):

    snacks = Snack.objects.all()
    s = []
    for snack in snacks :
        formatted_snack = {
            'id' : snack.id,
            'name' : snack.name,
            'price' : snack.price,
            'total_purchased_amount' : snack.total_purchased_amount,
            'picture_url' : snack.picture_url,
            'brand' : snack.brand,
            'category' : snack.category,
            'created_at' : snack.created_at,
            'quantity' : snack.quantity,
            'avg' : Snack.objects.avg_rating(snack)
        }
        s.append(formatted_snack)
        s = sorted(s, key=itemgetter('avg'))
        s.reverse()

    context ={
    'snacks': s,
    'user' : User.objects.filter(id=request.session['current_user'])[0]
    }

    return render(request, 'snacks/index.html', context)


def mostreviewed(request):

    snacks = Snack.objects.all()
    s = []
    for snack in snacks :
        formatted_snack = {
            'id' : snack.id,
            'name' : snack.name,
            'price' : snack.price,
            'total_purchased_amount' : snack.total_purchased_amount,
            'picture_url' : snack.picture_url,
            'brand' : snack.brand,
            'category' : snack.category,
            'created_at' : snack.created_at,
            'quantity' : snack.quantity,
            'avg' : Snack.objects.avg_rating(snack),
            'count' : snack.review_snack.count()
        }
        s.append(formatted_snack)
        s = sorted(s, key=itemgetter('count'))
        s.reverse()


    context ={
    'snacks': s,
    'user' : User.objects.filter(id=request.session['current_user'])[0]
    }


    return render(request, 'snacks/index.html', context)

def quantity(request, id):
    snack = Snack.objects.filter(id=id)[0]
    if str(id) in request.session['cart'] :

apps/snacks/templates/snacks/cart.html
<!DOCTYPE html> {% load static %}
<html>

<head>
        <title>Users</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
                crossorigin="anonymous">
        <link rel='stylesheet' href="{% static 'users/style.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>

<body>



        <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="{% url 'snacks:index' %}">Snacks</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarText">
                        <ul class="navbar-nav mr-auto">
                                <li class="nav-item">
                                        <a class="nav-link" href="{% url 'users:show' user.id %}">Account</a>
                                </li>
                                {% if user.is_admin %}
                                <li class="nav-item">
                                        <a class="nav-link" href="{% url 'snacks:new' %}">Add Snack</a>
                                    </li>
                                <li class="nav-item">
                                        <a style='color:rgb(187, 49, 49);' class="nav-link" href="{% url 'snacks:cart' %}">Shopping Cart</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'users:admin' %}">Add Admins</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'snacks:inventory' %}">Inventory</a>
                                </li>
                                {% endif %}
                                <li class="nav-item">
                                        <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                                </li>
                        </ul>
                        <span class="navbar-text">
                                <form class="form-inline" action="{% url 'snacks:search' %}" method="POST">
                                        {% csrf_token %}

                                        <input class="form-control mr-sm-2" type="search" name='search' placeholder="Search snack.." aria-label="Search">
                                        <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>

                                </form>
                        </span>
                </div>
        </nav>
        <br>

        <div class="container">
                <h1>Your Cart</h1>
                <br>
                <div class="row">
                        {% for snack in cart.itervalues %}
                        <div class="col" style='margin-left: 18px; margin-top: 20px;'>
                                <div class="card" style="width: 18em">
                                        <div class="img-responsive img-thumbnail ratio-4-3" style="height:18em;background:url({{snack.picture_url}}) no-repeat;background-size:contain;background-position:center"></div>
                                        <div class="card-body">
                                                <h5>
                                                        <a href="{% url 'snacks:show' snack.id %}">{{snack.name}}</a>
                                                </h5>
                                                <p>Category: {{snack.category}}</p>
                                                <p>Brand: {{snack.brand}}</p>
                                                <form action="{% url 'snacks:quantity' snack.id %}" method="POST">
                                                        {% csrf_token %}
                                                        <div class="row">
                                                    <input type="number" style="width:60px; margin-left: 15px;" class="form-control"  name="quantity" value="{{snack.quantity}}">
                                                    <input type="submit" class="btn btn-info" style="width:180px; margin-left: 5px;" value="Add Quantity">
                                                </div>
                                                </form><br>
                                                <form action="{% url 'snacks:destroysnack' snack.id %}" method="POST">
                                                        {% csrf_token %}

                                                        <input style='width:245px' class="btn btn-danger" type="submit" value="Remove from Cart">
                                                </form>

                                        </div>
                                </div>
                        </div>
                        
                        <br> {% endfor %}
                        
                </div><br>
                <form class="text-center" action="{% url 'snacks:checkout' %}" action="POST">
                        <input class='btn btn-dark' type="submit" value="Checkout">
                    </form>
        </div>
</body>

</html>

apps/snacks/templates/snacks/index.html
<!DOCTYPE html> {% load static %}
<html>

<head>
    <title>Users</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
        crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
        crossorigin="anonymous"></script>
    <link rel='stylesheet' href="{% static 'users/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" style='color:rgb(187, 49, 49);' href="{% url 'snacks:index' %}">Snacks</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:show' user.id %}">Account</a>
                </li>
                {% if user.is_admin %}
                <li class="nav-item">
                        <a class="nav-link" href="{% url 'snacks:new' %}">Add Snack</a>
                    </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'snacks:cart' %}">Shopping Cart</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:admin' %}">Add Admins</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'snacks:inventory' %}">Inventory</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                </li>
            </ul>
            <span class="navbar-text">
                <form class="form-inline" action="{% url 'snacks:search' %}" method="POST">
                    {% csrf_token %}

                    <input class="form-control mr-sm-2" type="search" name='search' placeholder="Search snack.." aria-label="Search">
                    <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>

                </form>
            </span>
        </div>
    </nav>
    <br>

    <div class="container">





        <div class="card" style="margin:0 auto">
            <h5 class="card-header text-center"  >
                <a style="margin-right:10%;margin-left:5%;" href="{% url 'snacks:index' %}">All</a>
                <a style="margin-right:10%" href="{% url 'snacks:newlyadded' %}">New</a>
                <a style="margin-right:10%" href="{% url 'snacks:top' %}">Top Rated</a>
                <a style="margin-right:10%" href="{% url 'snacks:mostreviewed' %}">Most Reviewed</a>
            </h5>
        </div>
        <div class="card-body">
            <div class="row">
                {% if snacks.count > 0 %} {% for snack in snacks %}

                <div class="col" style='margin-left: 18px; margin-top: 20px;'>
                    <div class="card" style="width: 18em">
                        <div class="img-responsive img-thumbnail ratio-4-3" style="height:18em;background:url({{snack.picture_url}}) no-repeat;background-size:contain;background-position:center"></div>
                        <div class="card-body">
                            <h5>
                                <a href="{% url 'snacks:show' snack.id %}">{{snack.name}}</a>
                            </h5>

                            <p>Category: {{snack.category.name}}</p>
                            <p>Brand: {{snack.brand.name}}</p>
                            <p>Total Purchased: {{snack.total_purchased_amount}}</p>
                            <p>Average Rating: {{ snack.avg }}</p>
                            {% if user.is_admin %}

                            <form action="{% url 'snacks:add' snack.id %}" method="POST">

                                {% csrf_token %}

                                <input type="submit" style="width:245px;" class="btn btn-success" value="Add to Cart">
                            </form>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %} {% endif %}
            </div>


        </div>



    </div>





</body>

</html>

apps/snacks/templates/snacks/inventory.html
<!DOCTYPE html> {% load static %}
<html>

<head>
    <title>Users</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
        crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
        crossorigin="anonymous"></script>
    <link rel='stylesheet' href="{% static 'users/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'snacks:index' %}">Snacks</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'snacks:new' %}">Add Snack</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:show' user.id %}">Account</a>
                </li>
                {% if user.is_admin %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'snacks:cart' %}">Shopping Cart</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:admin' %}">Add Admins</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" style='color:rgb(187, 49, 49);' href="{% url 'snacks:inventory' %}">Inventory</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                </li>
            </ul>
            <span class="navbar-text">
                <form class="form-inline" action="{% url 'snacks:search' %}" method="POST">
                    {% csrf_token %}

                    <input class="form-control mr-sm-2" type="search" name='search' placeholder="Search snack.." aria-label="Search">
                    <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>

                </form>
            </span>
        </div>
    </nav>
    <br>

<div class="container">
    
    <div class="card-body">
        <div class="row">
            {% if snacks.count > 0 %} {% for snack in snacks %}

            <div class="col" style='margin-left: 18px; margin-top: 20px;'>
                <div class="card"  style="width: 18em">
                    <div class="img-responsive img-thumbnail ratio-4-3" style="height:18em;background:url({{snack.picture_url}}) no-repeat;background-size:contain;background-position:center"></div>
                    <div class="card-body">
                        <h5>
                            <a href="{% url 'snacks:show' snack.id %}">{{snack.name}}</a>
                        </h5>
                        
                        <p>Category: {{snack.category.name}}</p>
                        <p>Brand: {{snack.brand.name}}</p>
                        <p>Total Purchased: {{snack.total_purchased_amount}}</p>
                        <p>Average Rating: {{ snack.avg }}</p>
                        <form action="{% url 'snacks:quantity' snack.id %}" method="POST">
                                {% csrf_token %}
                            <div class="row">
                                    <input type="number" style="width:60px; margin-left: 15px;" class="form-control"  name="quantity" value="{{snack.quantity}}">
                                    <input type="submit" class="btn btn-info" style="width:180px; margin-left: 5px;" value="Update Quantity">
                                </div>
                        </form>
                        <br>
                        {% if user.is_admin %}
                
                        <form action="{% url 'snacks:add' snack.id %}" method="POST">
                      
                            {% csrf_token %}
                        
                            <input type="submit" style="width:245px;" class="btn btn-success" value="Add to Cart">
                        </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %} {% endif %}
        </div>


    </div>



</div>





</body>

</html>